export const sourceCommit = "9e28222";

export const sourceBase = "modules/module-01-industrial-demand-generation";

export const workshopPlan = {
  format: "3-hour instructor-led workshop",
  totalMinutes: 180,
  teachingMinutes: 178,
  bufferMinutes: 2,
  instructorRule:
    "Slides are projection prompts. The instructor explains the depth, runs the diagnostic, and uses the workbook for artifact capture.",
};

export const commonIntegrativeQuestions = [
  "How does this affect sales?",
  "What signal would prove this is working?",
  "What would RevOps need to track?",
  "What content would help the buyer move forward?",
  "What assumption would a human reviewer challenge here?",
  "What would make this fail in an industrial company?",
];

export const lessons = [
  {
    id: "01",
    deckTitle: "Lesson 01 - Industrial Demand Generation Foundations",
    lessonTitle: "Industrial Demand Generation Foundations",
    slug: "lesson-01-industrial-demand-generation-foundations",
    shortTitle: "Foundations",
    timebox: "20 min",
    lessonFile: `${sourceBase}/lessons/01-industrial-demand-generation-foundations.md`,
    diagram: "01-industrial-demand-generation-operating-system.svg",
    supportingDiagrams: ["02-demand-states-and-routing.svg"],
    artifact: "Demand system diagnostic with three priority repairs",
    nextLesson: "Lesson 02 - Industrial Buyer Reality",
    promise:
      "Diagnose whether the company has a demand generation engine or only scattered marketing activity, lead capture, and sales heroics.",
    output:
      "One focus repair, one content or distribution repair, and one signal, owner, or cadence repair.",
    why: [
      "Industrial demand often exists before it is visible in a form, RFQ, or sales call.",
      "Buyers learn through consultants, distributors, exhibitions, peers, technical experts, and internal committees.",
      "Lead volume can rise while high-fit account movement stays flat.",
      "The operating system must connect trust, education, distribution, signal interpretation, buyer enablement, and weekly cadence.",
    ],
    frameworkTitle: "The demand engine only works when all seven jobs connect.",
    framework: [
      "Revenue goal and market focus",
      "ICP and buying committee",
      "MOIN and proof assets",
      "Trusted distribution",
      "Account-level signals",
      "Signal routing and buyer enablement",
      "Weekly learning loop",
    ],
    mentalModelTitle: "Separate the four motions before diagnosing the system.",
    mentalModel: [
      { label: "Creation", detail: "Teach the market why the problem or opportunity matters." },
      { label: "Distribution", detail: "Move insight through channels the buyer already trusts." },
      { label: "Capture", detail: "Interpret account-level evidence by fit, role, state, and strength." },
      { label: "Enablement", detail: "Help champions move the committee when the supplier is not in the room." },
    ],
    exampleTitle: "Composite food processing equipment supplier",
    example: [
      "The team attends exhibitions, collects visiting cards, posts product images, and celebrates inquiry volume.",
      "Sales complains that most RFQs are low quality and price-led.",
      "The repair is to focus on export-oriented snack manufacturers with throughput, oil efficiency, hygiene, or export-quality triggers.",
      "The operating measure becomes target account progression, not inquiry count alone.",
    ],
    diagnosticLead: "Where is the current system confusing activity with account movement?",
    diagnosticPrompts: [
      "Are we measuring leads or movement of high-fit accounts?",
      "Do we know which buying committee roles are engaging?",
      "Can sales explain why an account should be acted on now?",
      "Do we have content for content, solution, and vendor demand?",
      "Does RevOps capture source, state, strength, owner, SLA, and next action?",
    ],
    exerciseTitle: "Demand system diagnostic",
    exerciseTime: "6 min individual, 4 min pair review",
    exerciseSteps: [
      "Choose one manufacturing or export category.",
      "Score the nine system layers: market focus, ICP, demand creation, distribution, intelligence, activation, enablement, cadence.",
      "Name one repair in focus, one in content or distribution, and one in signal, owner, or cadence.",
    ],
    critique: [
      "Is the weakness a focus, content, distribution, routing, enablement, or cadence problem?",
      "What is the commercial consequence?",
      "Which buying role is affected?",
      "What would sales need before acting?",
      "What would RevOps need to capture?",
    ],
    draftingBrief:
      "Using the selected category, current assets, current channels, sales feedback, and CRM fields, classify the current demand motion as demand creation, demand capture, lead collection, or mixed. Identify the weakest operating layer, one practical repair that can start within two weeks, one account-level signal to track, and the validation questions that require sales, RevOps, SME, or leadership input.",
    draftingStandards: [
      "Names the missing layer",
      "Explains the anti-pattern and commercial risk",
      "Defines signal, owner, and cadence",
      "Lists field-validation questions",
    ],
    qualityControl: [
      "Reject more-content recommendations with no distribution path.",
      "Reject lead magnets before buyer trust exists.",
      "Reject impressions, traffic, likes, and MQLs as primary success.",
      "Reject activation before state and signal strength are known.",
      "Reject invented named-company examples.",
    ],
    revopsTitle: "The diagnostic must become inspectable fields.",
    revops: [
      "Account fit",
      "Demand state",
      "Signal source and strength",
      "Buying role",
      "Progression state",
      "Owner, SLA, and next action",
    ],
    failureModes: [
      ["Lead-gen disguise", "Forms and MQLs dominate", "Reset around account movement"],
      ["Campaign calendar thinking", "Content planned by month", "Rebuild around MOIN and sales use"],
      ["Owned-channel dependency", "Publishing without circulation", "Add expert, sales, partner, event, and association paths"],
      ["RevOps invisibility", "No signal object or progression state", "Define fields and weekly cadence board"],
    ],
    finalArtifact: [
      "One category or segment focus",
      "Current-state diagnosis across operating layers",
      "Three priority repairs",
      "One account movement signal",
      "One RevOps tracking requirement",
      "One sales behavior change",
      "One anti-pattern risk",
    ],
    transition:
      "Once the room agrees that movement matters more than activity, the next question is who inside the buying organization must move.",
  },
  {
    id: "02",
    deckTitle: "Lesson 02 - Industrial Buyer Reality",
    lessonTitle: "Industrial Buyer Reality",
    slug: "lesson-02-industrial-buyer-reality",
    shortTitle: "Buyer Reality",
    timebox: "20 min",
    lessonFile: `${sourceBase}/lessons/02-industrial-buyer-reality.md`,
    diagram: "03-industrial-buyer-committee-map.svg",
    supportingDiagrams: ["09-buyer-enablement-loop.svg"],
    artifact: "Buyer reality and committee map",
    nextLesson: "Lesson 03 - ICP, Segments, And Demand Focus",
    promise:
      "Map the real industrial buying committee, identify what each role needs to believe, and define the proof assets needed to move the account.",
    output: "A committee map with concerns, blockers, proof needs, enablement assets, and owners.",
    why: [
      "Industrial buyers rarely buy alone.",
      "The visible contact may like the solution while quality, finance, procurement, maintenance, or leadership remains unconvinced.",
      "Most deal stalls are missing internal proof, not missing follow-up.",
      "Buyer enablement matters because the champion sells internally when the supplier is absent.",
    ],
    frameworkTitle: "Buyer enablement asks what the account must believe.",
    framework: [
      "Visible champion",
      "Decision maker",
      "Technical evaluator",
      "Production or operations",
      "Quality, validation, or compliance",
      "Maintenance and service",
      "Procurement, finance, leadership, consultants, distributors",
    ],
    mentalModelTitle: "Sales enablement and buyer enablement are different jobs.",
    mentalModel: [
      { label: "Seller focus", detail: "What should sales say in the meeting?" },
      { label: "Buyer focus", detail: "What must the champion repeat internally?" },
      { label: "Seller asset", detail: "A better pitch deck." },
      { label: "Buyer asset", detail: "Role-specific proof, risk reduction, and internal case logic." },
    ],
    exampleTitle: "Composite regulated packaging machinery supplier",
    example: [
      "A production head at a pharma packaging plant wants line efficiency and faster changeover.",
      "Sales sends a proposal and follows up. The deal stalls.",
      "Hidden concerns remain across quality, engineering, finance, procurement, and leadership.",
      "The repair is validation proof, implementation roadmap, lifecycle cost logic, vendor comparison, and cost-of-delay case.",
    ],
    diagnosticLead: "Who must believe what before this account can move?",
    diagnosticPrompts: [
      "Who is the visible champion?",
      "Which roles can block the decision?",
      "Which roles are invisible today?",
      "What does each role fear?",
      "What proof can the champion circulate internally?",
      "What committee coverage should RevOps inspect?",
    ],
    exerciseTitle: "Buying committee map",
    exerciseTime: "6 min map, 4 min proof-gap review",
    exerciseSteps: [
      "List at least five roles for the selected category.",
      "For each role, write current belief, required belief, proof needed, asset, and owner.",
      "Mark which roles are mapped, engaged, enabled, missing, or blockers.",
    ],
    critique: [
      "Does the map separate roles instead of compressing them into one persona?",
      "Does it include blockers, not only supporters?",
      "Does each critical role have a circulatable proof asset?",
      "Does it include procurement and finance before late-stage negotiation?",
      "Does it account for consultants, distributors, or project advisors where relevant?",
    ],
    draftingBrief:
      "For the selected industrial category, map buying committee roles, role concerns, proof needs, likely blocker hypotheses, buyer-circulatable enablement assets, and unknowns that require sales or SME validation. Do not invent a named-company case.",
    draftingStandards: [
      "Includes operational, technical, commercial, quality, finance, procurement, leadership, and ecosystem roles where relevant",
      "States real decision risk, not generic persona pain",
      "Names specific proof or evidence",
      "Separates fact, assumption, and unknown",
    ],
    qualityControl: [
      "Reject neat personas that do not match the category.",
      "Reject maps that ignore quality, maintenance, procurement, finance, or leadership.",
      "Reject generic concerns like cost without the underlying risk.",
      "Reject sales decks when the buyer needs role-specific proof.",
      "Reject named-company examples presented as evidence.",
    ],
    revopsTitle: "Committee coverage must be visible account by account.",
    revops: [
      "Known buying role",
      "Role coverage status",
      "Proof asset shared",
      "Committee gap",
      "Champion strength",
      "Blocker risk",
      "Next committee action",
    ],
    failureModes: [
      ["One-person persona", "All content targets the decision maker", "Map real roles and proof needs"],
      ["Late procurement surprise", "Procurement appears only at quote stage", "Create vendor comparison logic earlier"],
      ["Technical proof gap", "Interest stalls after demo", "Build application, validation, integration, or test proof"],
      ["Champion unsupported", "Main contact cannot sell internally", "Give internal case and objection handler"],
    ],
    finalArtifact: [
      "At least five committee roles",
      "Current and required belief for each role",
      "One proof need per critical role",
      "One enablement asset per blocker or missing role",
      "Owner for each asset or delivery action",
      "Committee coverage gaps for RevOps",
    ],
    transition:
      "The committee map exposes whose belief must change. The next lesson decides which accounts deserve that much operating effort.",
  },
  {
    id: "03",
    deckTitle: "Lesson 03 - ICP, Segments, And Demand Focus",
    lessonTitle: "ICP, Segments, And Demand Focus",
    slug: "lesson-03-icp-segments-and-demand-focus",
    shortTitle: "ICP Focus",
    timebox: "22 min",
    lessonFile: `${sourceBase}/lessons/03-icp-segments-and-demand-focus.md`,
    diagram: "04-icp-focus-and-disqualification.svg",
    supportingDiagrams: ["27-executive-sponsor-decision-loop.svg"],
    artifact: "ICP and disqualification scorecard",
    nextLesson: "Lesson 04 - MOIN: Map Of Informational Needs",
    promise:
      "Choose a narrow industrial demand focus for a 90-day pilot, define ICP triggers and exclusions, and stop wasting effort on visible but weak accounts.",
    output: "An ICP and disqualification scorecard plus a written 90-day demand focus statement.",
    why: [
      "Industrial demand generation is resource-intensive: SME input, trusted distribution, sales context, proof, and RevOps tracking all cost effort.",
      "Broad TAM language turns content generic and pollutes signal routing.",
      "A pilot learns faster when the segment is narrow enough to produce specific questions, proof, access paths, and disqualification.",
      "Focus is revenue discipline, not positioning theater.",
    ],
    frameworkTitle: "A real industrial ICP is more than firmographics.",
    framework: [
      "Sector or category",
      "Account type",
      "Trigger or timing",
      "Technical fit",
      "Commercial fit",
      "Buying process",
      "Access path",
      "Disqualification",
    ],
    mentalModelTitle: "Pick the segment where the pilot can create movement.",
    mentalModel: [
      { label: "Pain intensity", detail: "Is the problem worth solving now?" },
      { label: "Trigger visibility", detail: "Can timing be detected?" },
      { label: "Access path", detail: "Can trusted channels reach the committee?" },
      { label: "Proof availability", detail: "Can evidence be built quickly enough?" },
    ],
    exampleTitle: "Composite precision fabrication supplier",
    example: [
      "The company says its market is all OEMs that outsource manufacturing.",
      "That is too broad for demand generation and creates weak content, distribution, and routing.",
      "The sharper pilot ICP is export-oriented equipment OEMs needing medium-to-high complexity fabricated components with tolerance control, documentation, and repeat production potential.",
      "Exclude one-off fabrication jobs, no-repeat accounts, and lowest-price procurement comparisons.",
    ],
    diagnosticLead: "Which accounts are valuable enough, specific enough, and reachable enough to justify demand generation effort?",
    diagnosticPrompts: [
      "What trigger makes the problem current?",
      "Which roles must be educated?",
      "What proof already exists?",
      "What account types create low-quality RFQs?",
      "Where does sales currently waste time?",
      "What segment can produce learning in 90 days?",
    ],
    exerciseTitle: "Segment comparison and focus statement",
    exerciseTime: "7 min segment scoring, 5 min focus statement",
    exerciseSteps: [
      "Compare three candidate segments by fit evidence, trigger evidence, access path, value potential, and disqualification risk.",
      "Choose one 90-day focus segment.",
      "Write the demand focus statement and at least five rejection rules.",
    ],
    critique: [
      "Is the ICP narrow enough for 90 days?",
      "What accounts should be excluded immediately?",
      "What signal would prove the segment is moving?",
      "What buyer roles must be visible?",
      "What content becomes specific because the ICP is narrow?",
      "What will leadership be tempted to broaden too early?",
    ],
    draftingBrief:
      "Compare three candidate industrial segments by fit, trigger, access, commercial value, committee feasibility, proof availability, and pilot feasibility. Recommend one 90-day ICP, explain why it is narrow enough, define explicit disqualification rules, and list risks or assumptions the team must validate.",
    draftingStandards: [
      "Ranks by fit, trigger, access, value, and feasibility",
      "Explains why the chosen segment is narrow enough",
      "Includes explicit rejection rules",
      "Names likely committee roles and demand signals",
    ],
    qualityControl: [
      "Reject market size as the main reason.",
      "Reject broad categories without triggers.",
      "Reject segments with no commercial value threshold.",
      "Reject digital-access assumptions where relationship channels dominate.",
      "Reject any pilot without disqualification.",
    ],
    revopsTitle: "RevOps should prove that focus is real.",
    revops: [
      "ICP fit score",
      "Fit reason",
      "Trigger type",
      "Trigger evidence and date",
      "Pilot segment",
      "Access path",
      "Disqualification reason",
      "Progression state",
    ],
    failureModes: [
      ["Broad market fantasy", "We serve all manufacturers", "Narrow by trigger, application, value, and access"],
      ["Logo wish list", "Accounts chosen because they are famous", "Require fit, trigger, proof, and access"],
      ["Price-led inbound trap", "Weak-fit RFQs consume effort", "Route low-fit inquiries differently"],
      ["No exclusion logic", "Every account stays in the system", "Add downgrade and disqualification rules"],
    ],
    finalArtifact: [
      "90-day ICP focus statement",
      "Priority sector and account profile",
      "Trigger, technical fit, commercial fit, geography, and buying process",
      "Access path and buying committee assumptions",
      "At least five disqualification rules",
      "Account progression signal to measure",
    ],
    transition:
      "A focused ICP makes the next work possible: mapping the actual questions that block movement inside that segment.",
  },
  {
    id: "04",
    deckTitle: "Lesson 04 - MOIN: Map Of Informational Needs",
    lessonTitle: "MOIN: Map Of Informational Needs",
    slug: "lesson-04-moin-map-of-informational-needs",
    shortTitle: "MOIN",
    timebox: "22 min",
    lessonFile: `${sourceBase}/lessons/04-moin-map-of-informational-needs.md`,
    diagram: "05-moin-to-content-roadmap.svg",
    supportingDiagrams: ["20-content-audit-and-gap-prioritization.svg"],
    artifact: "MOIN grid",
    nextLesson: "Lesson 05 - Content Engine For Industrial Demand",
    promise:
      "Convert buyer uncertainty into a role-specific content and proof roadmap.",
    output:
      "A MOIN grid that maps questions by role and demand state, then translates them into content, sales use, signal design, and proof gaps.",
    why: [
      "Industrial buyers delay decisions when information does not reduce risk.",
      "Content topics are weak unless they map to buyer uncertainty, role, demand state, and proof need.",
      "MOIN prevents product-first content and premature vendor claims.",
      "The map tells marketing what to build, sales how to use it, and RevOps what engagement means.",
    ],
    frameworkTitle: "MOIN maps buyer uncertainty by role and demand state.",
    framework: [
      "Choose the ICP segment",
      "List committee roles",
      "Write content-demand questions",
      "Write solution-demand questions",
      "Write vendor-demand questions",
      "Identify proof assets",
      "Define sales use and signal meaning",
    ],
    mentalModelTitle: "Every substantial asset must answer four operating questions.",
    mentalModel: [
      { label: "Market", detail: "Which segment or account cluster is this for?" },
      { label: "Objective", detail: "What belief, signal, or movement should it create?" },
      { label: "Insight", detail: "What non-obvious lesson does it teach?" },
      { label: "Next action", detail: "What should the buyer or account team do after engagement?" },
    ],
    exampleTitle: "Composite inspection and automation-adjacent supplier",
    example: [
      "The weak plan is automation trends, product demos, brochure excerpts, and ads to a form.",
      "The MOIN plan starts with defect cost, inspection method comparison, validation proof, integration criteria, TCO, and procurement specification.",
      "Questions are separated for quality, plant, engineering, finance, and procurement roles.",
      "The result is demand generation because it educates, equips sales, creates signals, and reduces internal risk.",
    ],
    diagnosticLead: "What does each buyer role need to understand before the account can move to the next demand state?",
    diagnosticPrompts: [
      "What does the buyer not yet believe?",
      "Which role is under-educated?",
      "Which question blocks internal consensus?",
      "Which question appears repeatedly in sales calls?",
      "What proof would shorten the internal debate?",
      "What engagement would create a meaningful signal?",
    ],
    exerciseTitle: "Build the MOIN grid",
    exerciseTime: "8 min grid, 4 min prioritization",
    exerciseSteps: [
      "Pick five committee roles.",
      "Write content, solution, and vendor-demand questions for each.",
      "Name the required asset, sales use, and signal created.",
      "Prioritize the top five assets by account movement potential.",
    ],
    critique: [
      "Mark each question green, yellow, or red.",
      "Ask which role would ask it.",
      "Ask which demand state it belongs to.",
      "Ask which decision risk it reduces.",
      "Ask what proof makes the answer credible.",
      "Ask how sales would use the answer.",
    ],
    draftingBrief:
      "Draft or repair a MOIN grid for the selected ICP. Separate buyer questions by role and demand state. Recommend assets, sales use, RevOps signal meaning, assumptions, and field-validation questions. Avoid generic content topics and vendor-demand claims before buyer belief exists.",
    draftingStandards: [
      "Questions separated by role and demand state",
      "One asset per critical question or proof gap",
      "Sales use without pitching too early",
      "Signal meaning and routing implication",
      "Assumptions and validation questions",
    ],
    qualityControl: [
      "Reject generic topics and content pillars.",
      "Reject output that ignores committee roles.",
      "Reject vendor-demand assets placed too early.",
      "Reject missing compliance, procurement, implementation, or finance concerns.",
      "Reject polished language with no industrial specificity.",
    ],
    revopsTitle: "MOIN creates content metadata and signal meaning.",
    revops: [
      "Asset demand state",
      "Buyer role served",
      "Account cluster",
      "Question answered",
      "Sales use case",
      "Signal meaning",
      "Next action",
    ],
    failureModes: [
      ["Topic brainstorm", "Blog ideas with no role", "Map role, question, demand state, and proof"],
      ["Product-first content", "Assets start with supplier features", "Start from buyer uncertainty"],
      ["Missing sales use", "Assets are ignored by sales", "Add sales context and use case"],
      ["No signal design", "Engagement changes no action", "Define signal strength and routing rule"],
    ],
    finalArtifact: [
      "At least five committee roles",
      "Questions across content, solution, and vendor demand",
      "One required asset per critical role",
      "Sales use for each asset",
      "Signal created by engagement",
      "Top five prioritized assets for the pilot",
    ],
    transition:
      "MOIN tells us what buyers need to learn. The next lesson turns those questions into a content engine sales will actually use.",
  },
  {
    id: "05",
    deckTitle: "Lesson 05 - Content Engine For Industrial Demand",
    lessonTitle: "Content Engine For Industrial Demand",
    slug: "lesson-05-content-engine-for-industrial-demand",
    shortTitle: "Content Engine",
    timebox: "22 min",
    lessonFile: `${sourceBase}/lessons/05-content-engine-for-industrial-demand.md`,
    diagram: "06-content-engine-to-signal.svg",
    supportingDiagrams: ["20-content-audit-and-gap-prioritization.svg"],
    artifact: "Content plan by demand state",
    nextLesson: "Lesson 06 - Distribution: The Missing Half",
    promise:
      "Turn MOIN into an industrial content engine that creates trust, supports sales, produces account signals, and reduces buying committee risk.",
    output:
      "A content plan by demand state with SME input, sales use, distribution path, and signal design for each asset.",
    why: [
      "Industrial content is not a publishing calendar.",
      "Useful assets help buyers understand problems, compare approaches, reduce risk, and explain the case internally.",
      "The same assets help sales warm accounts, interpret demand state, support champions, and identify proof gaps.",
      "Content without sales use, distribution, or signal design becomes volume.",
    ],
    frameworkTitle: "Every asset needs a job.",
    framework: [
      "Problem education",
      "Application education",
      "Decision criteria",
      "Proof",
      "Buyer enablement",
      "Demand capture",
      "Sales support",
    ],
    mentalModelTitle: "Build by demand state, not by calendar slot.",
    mentalModel: [
      { label: "Content demand", detail: "Risk guide, trend note, benchmark, process explainer." },
      { label: "Solution demand", detail: "Selection guide, calculator, checklist, application framework." },
      { label: "Vendor demand", detail: "Technical dossier, validation proof, TCO, implementation plan." },
      { label: "Buyer enablement", detail: "Internal case, objection handler, procurement or finance proof." },
    ],
    exampleTitle: "Composite transformer and electrical equipment supplier",
    example: [
      "The current asset base is brochures, certificates, and tender responses.",
      "Sales says buyers compare price late and consultants often control specifications before the supplier enters.",
      "The upstream content engine covers lifecycle losses, specification clarity, service readiness, vendor comparison, and TCO.",
      "Each asset has a buyer role, demand state, sales use, and signal.",
    ],
    diagnosticLead: "Which content assets would make the buyer smarter, safer, and more able to move internally?",
    diagnosticPrompts: [
      "What buyer question appears before the RFQ?",
      "What objection appears repeatedly in sales calls?",
      "What proof does the champion need internally?",
      "Which committee role is under-served?",
      "Which asset requires SME insight before any draft is credible?",
      "Which existing asset should be repaired instead of replaced?",
    ],
    exerciseTitle: "Build the first-five content plan",
    exerciseTime: "8 min asset plan, 4 min priority call",
    exerciseSteps: [
      "Choose at least two content-demand assets, two solution-demand assets, and one vendor-demand or buyer-enablement asset.",
      "For each asset, define buyer question, SME input, sales use, distribution path, signal created, and quality risk.",
      "Label build now, repair, or later.",
    ],
    critique: [
      "Is the asset useful before the buyer is ready to talk to sales?",
      "Does it include field insight, technical proof, or SME judgment?",
      "Can sales use it without rewriting?",
      "Does it reduce a specific decision risk?",
      "Can it be distributed through a trusted channel?",
      "Would a serious industrial buyer respect it?",
    ],
    draftingBrief:
      "Turn the MOIN grid into a content plan. For each asset, name the buyer question, demand state, format, SME input, sales use, distribution path, signal design, and quality risk. Flag where human technical or field validation is required before drafting.",
    draftingStandards: [
      "Assets tied to role, question, and demand state",
      "Specific SME input required",
      "Sales use and account context",
      "Signal design and routing implication",
      "Distribution path and quality risk",
    ],
    qualityControl: [
      "Remove generic blog ideas.",
      "Remove product brochures disguised as education.",
      "Reject claims unsupported by proof.",
      "Reject assets without a distribution path.",
      "Reject assets sales cannot use.",
      "Reject technical claims without SME validation.",
    ],
    revopsTitle: "Content must connect to account movement.",
    revops: [
      "Asset ID",
      "Demand state",
      "Buyer role",
      "Account cluster",
      "Signal strength",
      "Sales use",
      "Next action",
      "Proof gap",
    ],
    failureModes: [
      ["Content volume strategy", "Many posts, little movement", "Prioritize by buyer uncertainty and signal value"],
      ["Product-first content", "Features before problem belief", "Build problem and solution education first"],
      ["Generic filler", "Polished generic language", "Require SME input and proof"],
      ["No distribution path", "Content sits on website", "Assign channel, owner, cadence, and sales motion"],
    ],
    finalArtifact: [
      "Two content-demand assets",
      "Two solution-demand assets",
      "One vendor-demand or buyer-enablement asset",
      "SME input requirement per asset",
      "Sales use per asset",
      "Distribution path per asset",
      "Signal design per asset",
    ],
    transition:
      "A good asset still fails if the right buyers never see it. The next lesson is the missing half: trusted distribution.",
  },
  {
    id: "06",
    deckTitle: "Lesson 06 - Distribution: The Missing Half",
    lessonTitle: "Distribution: The Missing Half",
    slug: "lesson-06-distribution-the-missing-half",
    shortTitle: "Distribution",
    timebox: "22 min",
    lessonFile: `${sourceBase}/lessons/06-distribution-the-missing-half.md`,
    diagram: "07-distribution-ecosystem.svg",
    supportingDiagrams: ["21-channel-selection-by-trust-and-stage.svg", "22-event-and-trade-show-demand-motion.svg", "23-distributor-and-partner-signal-motion.svg"],
    artifact: "Distribution and ecosystem plan",
    nextLesson: "Lesson 07 - Signal Routing And Demand Capture",
    promise:
      "Design an industrial distribution system that gets useful insight in front of the right accounts through trusted channels, not just owned publishing.",
    output:
      "A distribution and ecosystem plan with channel role, trust reason, demand state, owner, cadence, account signal, and follow-up rule.",
    why: [
      "Publishing is not distribution.",
      "Industrial demand moves through experts, sales, associations, exhibitions, distributors, consultants, project advisors, media, search, and referrals.",
      "Buyers trust field expertise and borrowed credibility more than generic company-page claims.",
      "Distribution must create account evidence, not just reach.",
    ],
    frameworkTitle: "Choose channels by buyer trust and decision stage.",
    framework: [
      "Expert profiles",
      "Sales sharing",
      "Associations and export bodies",
      "Trade shows and technical events",
      "Distributors and partners",
      "Consultants and advisors",
      "Industry publications",
      "Website, search, and proven paid amplification",
    ],
    mentalModelTitle: "Dark social needs a capture rule.",
    mentalModel: [
      { label: "Trusted channel", detail: "A buyer, partner, consultant, or sales person mentions an account, role, problem, timing, or referral." },
      { label: "Capture rule", detail: "Log source, role, demand state, strength, owner, and next action." },
      { label: "Operating risk", detail: "If it stays in chat, memory, or event notes, the system undercounts real demand." },
      { label: "Cadence", detail: "Review distribution evidence in the weekly account movement meeting." },
    ],
    exampleTitle: "Composite specialty process equipment supplier",
    example: [
      "Useful technical notes about repeatability and coating selection sit on the company blog.",
      "Buyers rarely see them before calling for price.",
      "The repair uses SME profile posts, sales sharing, association education, distributor proof notes, and retargeting of proven engaged accounts.",
      "The plan creates visibility, trust, and signals instead of simply publishing more.",
    ],
    diagnosticLead: "Where does the content need to circulate for the buyer to trust it and for the account team to detect movement?",
    diagnosticPrompts: [
      "Which channels already have buyer trust?",
      "Which channels can reach the committee?",
      "Which channels create observable account signals?",
      "Where is sales already in conversation?",
      "Where do distributors or consultants influence decisions?",
      "What should be captured after distribution?",
    ],
    exerciseTitle: "Distribution and ecosystem plan",
    exerciseTime: "8 min channel plan, 4 min ecosystem map",
    exerciseSteps: [
      "Select at least five channels for the first-five assets.",
      "For each, define trust reason, demand state, owner, cadence, account signal, and follow-up rule.",
      "Map ecosystem nodes: associations, events, distributors, consultants, media, technical communities, customer peer groups.",
    ],
    critique: [
      "Does the plan rely too heavily on owned publishing?",
      "Are expert profiles used where trust matters?",
      "Is sales distributing insight, not just asking for meetings?",
      "Are events designed before, during, and after the show?",
      "Are partners given proof and routing rules?",
      "Does every channel create observable account evidence?",
    ],
    draftingBrief:
      "Draft a channel mix for the selected ICP and first-five assets. Tie every channel to buyer trust, demand state, owner, realistic cadence, account-level signal, routing implication, and failure risk. Do not recommend more channels than the team can operate.",
    draftingStandards: [
      "Channel tied to buyer trust and demand state",
      "Owner named: sales, marketing, SME, distributor, partner, or leadership",
      "Realistic cadence",
      "Account-level signal",
      "Routing implication and risk",
    ],
    qualityControl: [
      "Repair channel lists that are too large to operate.",
      "Reject paid ads as a substitute for trust.",
      "Reject plans that ignore sales and partner distribution.",
      "Reject event plans without 72-hour routing.",
      "Reject company-page posting as the main motion.",
      "Reject distribution with no owner or cadence.",
    ],
    revopsTitle: "Distribution creates source evidence.",
    revops: [
      "Distribution channel",
      "Asset circulated",
      "Account or cluster",
      "Buying role",
      "Demand state",
      "Signal strength",
      "Source type",
      "Follow-up rule",
    ],
    failureModes: [
      ["Publishing-only", "Content exists but buyers never see it", "Build channel plan and owner model"],
      ["Company-page dependency", "Low reach and low trust", "Move insight through experts and sales"],
      ["Event leakage", "Meetings happen but signals are not routed", "Create event signal board and 72-hour routing"],
      ["Partner noise", "Distributors send weak leads", "Train ICP, proof, and routing rules"],
    ],
    finalArtifact: [
      "At least five channels",
      "Trust reason for each channel",
      "Demand state served",
      "Owner and cadence",
      "Account-level signal",
      "Follow-up rule",
      "One ecosystem map",
    ],
    transition:
      "Distribution makes movement visible. The next lesson prevents the team from mistaking every visible signal for buying intent.",
  },
  {
    id: "07",
    deckTitle: "Lesson 07 - Signal Routing And Demand Capture",
    lessonTitle: "Signal Routing And Demand Capture",
    slug: "lesson-07-signal-routing-and-demand-capture",
    shortTitle: "Signal Routing",
    timebox: "24 min",
    lessonFile: `${sourceBase}/lessons/07-signal-routing-and-demand-capture.md`,
    diagram: "08-signal-routing-and-account-progression.svg",
    supportingDiagrams: ["24-revops-signal-object-and-data-model.svg"],
    artifact: "Signal-routing table with owner, SLA, next action, and false-positive risk",
    nextLesson: "Lesson 08 - Measurement, Cadence, And 90-Day Pilot",
    promise:
      "Classify industrial demand signals by account fit, demand state, buying role, and evidence strength, then route each signal to the right next action.",
    output:
      "A signal-routing table with owner, SLA, next action, false-positive risk, and opportunity review criteria.",
    why: [
      "The most expensive demand generation error is treating every signal as buying intent.",
      "Industrial engagement can mean learning, comparison, distributor checking, procurement research, or active supplier evaluation.",
      "Signals are useful only after interpretation.",
      "Routing protects sales from noise while ensuring strong vendor-demand evidence gets acted on quickly.",
    ],
    frameworkTitle: "Use four filters before assigning action.",
    framework: [
      "Account fit",
      "Demand state",
      "Buying committee role",
      "Evidence strength",
      "Then choose education, research, mapping, enablement, activation, opportunity review, or disqualification",
    ],
    mentalModelTitle: "Account progression is not a straight jump to opportunity.",
    mentalModel: [
      { label: "Cluster ICP", detail: "Fits target segment; need unknown." },
      { label: "Future Pipeline", detail: "Engagement or awareness; need unconfirmed." },
      { label: "Active Focus", detail: "Need, trigger, stakeholder, timing, or relationship evidence." },
      { label: "Opportunity", detail: "Declared requirement, value logic, champion, and next step." },
    ],
    exampleTitle: "Composite calibration and validation services provider",
    example: [
      "A quality coordinator reads one audit-readiness post. That is weak content demand.",
      "The same account returns to a calibration interval guide. Research the account and audit timing.",
      "A validation head attends a webinar and asks about documentation. Map committee and send validation proof.",
      "A plant head requests an audit readiness review. Strong vendor demand triggers Active Focus and sales action.",
    ],
    diagnosticLead: "Which signals deserve education, research, activation, opportunity review, or disqualification?",
    diagnosticPrompts: [
      "What is the account fit?",
      "What demand state does the signal represent?",
      "Which role created the signal?",
      "Is it weak, moderate, or strong?",
      "What is the false-positive risk?",
      "What is the SLA?",
    ],
    exerciseTitle: "Classify and route five signals",
    exerciseTime: "8 min routing table, 5 min opportunity criteria",
    exerciseSteps: [
      "Classify each signal by source, account fit, role, demand state, strength, owner, SLA, next action, and false-positive risk.",
      "Define opportunity review evidence: ICP fit, named stakeholder, need, value, demand state, next step, and committee risk.",
      "Downgrade weak or low-fit signals before sales receives them.",
    ],
    critique: [
      "Name one signal being over-routed to sales.",
      "Name one signal that deserves faster action.",
      "Name one signal that requires committee mapping.",
      "Name one signal that should be disqualified or low-touch nurtured.",
      "Name one missing field that would make routing unreliable.",
    ],
    draftingBrief:
      "Classify the signal table. For each signal, assign demand state, strength, progression state, owner, SLA, next action, false-positive concern, and missing evidence. Explain why the signal is or is not buying intent. Do not route weak engagement as an opportunity.",
    draftingStandards: [
      "Demand state with rationale",
      "Signal strength and progression state",
      "Owner and SLA",
      "Specific next action",
      "False-positive concern",
      "Missing evidence before escalation",
    ],
    qualityControl: [
      "Reject engagement equals intent.",
      "Reject skipped ICP fit checks.",
      "Reject routing that ignores buying role.",
      "Reject outreach without relevance.",
      "Reject weak signals escalated as opportunities.",
      "Reject strong vendor-demand signals left in nurture.",
    ],
    revopsTitle: "Signal routing needs a signal object or working board.",
    revops: [
      "Signal date",
      "Account",
      "Contact or role",
      "Signal source",
      "Asset or context",
      "Demand state and strength",
      "Fit and progression state",
      "Owner, SLA, next action",
      "False-positive risk",
    ],
    failureModes: [
      ["Intent inflation", "Every click becomes a lead", "Route by fit, state, role, and strength"],
      ["Weak sales handoff", "Sales receives names without context", "Provide signal reason and next action"],
      ["Signal decay", "Strong signal sits untouched", "Define owner and SLA"],
      ["CRM blindness", "Signals live in chats or notes", "Create signal object or shared board"],
    ],
    finalArtifact: [
      "Weak, moderate, and strong signal examples",
      "Content, solution, and vendor demand",
      "Source class and buying role",
      "Owner and SLA",
      "Next action",
      "False-positive risk",
      "Opportunity review criteria",
    ],
    transition:
      "Routing creates disciplined next actions. The final lesson turns those actions into weekly governance and a 90-day pilot decision.",
  },
  {
    id: "08",
    deckTitle: "Lesson 08 - Measurement, Cadence, And 90-Day Pilot",
    lessonTitle: "Measurement, Cadence, And 90-Day Pilot",
    slug: "lesson-08-measurement-cadence-and-90-day-pilot",
    shortTitle: "Cadence And Pilot",
    timebox: "26 min",
    lessonFile: `${sourceBase}/lessons/08-measurement-cadence-and-90-day-pilot.md`,
    diagram: "10-weekly-revenue-cadence.svg",
    supportingDiagrams: ["12-capstone-assembly-map.svg", "14-90-day-implementation-sprint.svg", "25-metrics-and-pipeline-quality.svg"],
    artifact: "Weekly cadence and 90-day pilot plan",
    nextLesson: "Capstone review and field implementation",
    promise:
      "Assemble prior artifacts into a 90-day Industrial Demand Generation Pilot and define the weekly revenue cadence that keeps sales, marketing, RevOps, leadership, and technical teams aligned.",
    output:
      "A weekly cadence model and pilot plan with success metrics, owners, evidence, and stop, repair, scale criteria.",
    why: [
      "Industrial demand generation becomes real only when the team inspects account movement every week.",
      "Revenue may not close inside 90 days, but the pilot can still prove movement, committee coverage, signal quality, and opportunity quality.",
      "Cadence is not reporting. It is a decision rhythm.",
      "The pilot must be narrow enough to learn before leadership decides to stop, repair, or scale.",
    ],
    frameworkTitle: "Measure movement, not volume.",
    framework: [
      "Target-account reach",
      "Engaged accounts by demand state",
      "Repeat engagement from ICP accounts",
      "Buying committee roles engaged",
      "Future Pipeline and Active Focus accounts",
      "Strong signals routed within SLA",
      "Sales conversations created by useful content",
      "Proof gaps found and repaired",
    ],
    mentalModelTitle: "The weekly meeting makes decisions from evidence.",
    mentalModel: [
      { label: "Progression", detail: "Which accounts moved state, and why?" },
      { label: "Routing", detail: "Which new signals need owner, SLA, or downgrade?" },
      { label: "Proof gaps", detail: "Which role or objection is blocking movement?" },
      { label: "Next commitments", detail: "What will be built, routed, repaired, or disqualified this week?" },
    ],
    exampleTitle: "Composite calibration and validation services provider",
    example: [
      "The pilot targets regulated manufacturers with audit or validation triggers.",
      "Revenue may not close in 90 days, so the team inspects reach, quality and validation roles engaged, audit-window signals, Future Pipeline accounts, Active Focus accounts, consultation requests, proof gaps, SLA completion, and disqualifications.",
      "The pilot succeeds if a repeatable motion is visible from education to signal routing to owner action to consultation, opportunity review, or qualified future pipeline.",
    ],
    diagnosticLead: "What will the team inspect every week so the pilot improves before the quarter ends?",
    diagnosticPrompts: [
      "Which accounts moved?",
      "What evidence caused movement?",
      "Which accounts stalled?",
      "Which buying roles are missing?",
      "Which signals were false positives?",
      "Which strong signals missed SLA?",
      "What decision does leadership need to make?",
    ],
    exerciseTitle: "Build the cadence and pilot outline",
    exerciseTime: "8 min cadence board, 6 min pilot phases",
    exerciseSteps: [
      "Build the weekly cadence agenda with evidence reviewed, owner, decision rule, and output.",
      "Draft the five pilot phases: scope, MOIN/content, distribution/signals, routing/activation, readout/decision.",
      "Define stop, repair, and scale criteria before launch.",
    ],
    critique: [
      "Are the metrics mostly leading indicators?",
      "Can RevOps capture the evidence?",
      "Are owners named?",
      "Are stop, repair, and scale criteria explicit?",
      "Does the cadence create decisions or only reporting?",
      "Does the pilot connect content, distribution, routing, sales action, and buyer enablement?",
    ],
    draftingBrief:
      "Assemble the 90-day pilot from prior artifacts. Include executive summary, phase plan, weekly cadence, success metrics, anti-pattern risks, stop-repair-scale criteria, and unresolved assumptions requiring field validation. Keep metrics focused on account movement and quality, not vanity activity.",
    draftingStandards: [
      "Clear revenue problem, focus, pilot logic, and decision request",
      "90-day sequence with owners and outputs",
      "Cadence with evidence and decisions",
      "Success metrics for movement, coverage, signal quality, sales use, and opportunity quality",
      "Stop, repair, scale criteria tied to evidence",
    ],
    qualityControl: [
      "Reject vanity metrics.",
      "Reject scale recommendations without proof.",
      "Reject plans with no RevOps fields or owner model.",
      "Reject campaign framing.",
      "Reject broad plans with no disqualification.",
      "Reject confident summaries that hide assumptions.",
    ],
    revopsTitle: "The cadence runs from boards, not memory.",
    revops: [
      "Account progression board",
      "Signal board",
      "Committee coverage",
      "Content and proof gap list",
      "Sales action tracker",
      "SLA tracker",
      "Pilot learning log",
    ],
    failureModes: [
      ["Reporting meeting", "Numbers reviewed without decisions", "Require decision rule and owner per item"],
      ["Vanity success", "Impressions or MQLs celebrated", "Measure movement and quality"],
      ["Sales disconnected", "Sales does not use content or signals", "Define sales role and weekly commitments"],
      ["Premature scale", "Leadership expands before proof", "Use stop, repair, scale criteria"],
    ],
    finalArtifact: [
      "ICP definition",
      "Buying committee map",
      "MOIN grid",
      "Content plan",
      "Distribution plan",
      "Signal-routing rules",
      "Weekly cadence",
      "Success metrics",
      "Anti-pattern risks",
      "Executive summary",
    ],
    transition:
      "The lesson sequence ends where field implementation begins: an executive sponsor can now approve, repair, or reject the pilot from evidence.",
  },
];
